spring:
  profiles:
    active: development
---
spring:
  profiles: development
  zipkin:
    base-url: http://localhost:9411/
  sleuth:
    sampler:
      percentage: 1.0
security:
  oauth2:
    client:
      client-id: acme
      access-token-uri: http://localhost:8181/uaa/oauth/token
      grant-type: client-credentials
      client-secret: acmesecret
      scope: openid
      client-authentication-scheme: header
  ignored: /**
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
---
spring:
  profiles: docker
  zipkin:
    base-url: http://zipkin:9411/
  sleuth:
    sampler:
      percentage: 1.0
security:
  oauth2:
    client:
      client-id: acme
      access-token-uri: http://user-service:8181/uaa/oauth/token
      grant-type: client-credentials
      client-secret: acmesecret
      scope: openid
      client-authentication-scheme: header
  ignored: /**
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/
---
spring:
  profiles: test
security:
  oauth2:
    resource:
      userInfoUri: http://localhost:8181/uaa/user
    client:
      client-id: acme
      access-token-uri: http://localhost:8181/uaa/oauth/token
      user-authorization-uri: http://localhost:8181/uaa/oauth/authorize
      grant-type: client-credentials
      client-secret: acmesecret
      scope: openid
