spring:
  profiles:
    active: development
---
spring:
  profiles: development
  application:
    name: edge-service
  zipkin:
    base-url: http://localhost:9411/
  sleuth:
    sampler:
      percentage: 1.0
zuul:
  ignored-services: '*'
  ignoredPatterns: /**/api/**
  routes:
    profile-service: /profile/**
    user-service: /user/**
security:
  oauth2:
    resource:
      userInfoUri: http://localhost:8181/uaa/user
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
---
spring:
  profiles: docker
  application:
    name: edge-service
  zipkin:
      base-url: http://zipkin:9411/
zuul:
  ignored-services: '*'
  ignoredPatterns: /**/api/**
  routes:
    profile-service: /profile/**
    user-service: /user/**
security:
  oauth2:
    resource:
      userInfoUri: http://${DOCKER_IP:192.168.99.100}:8181/uaa/user
  ignored: /catalog/**
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000
ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 60000
